version: '3.7'

services:


    

    app:
        build: 
            context: ./APP
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 --timeout=0 app:app 
        ports:
            - "5000:5000"
        environment:
            KEY_SECRET: "secret"
        volumes:
            - appdata:/var/www/
        

volumes:

    appdata:
        driver: local
        